### ISSUE TITLE
Fix mixin from augmenting lodash by using _.runInContext

### ISSUE THREAD

**Issue by jdalton** [jlmorgan/lodash-transpose#1]
You should use [_.runInContext](https://lodash.com/docs#runInContext) to avoid augmenting the `lodash` package.

``` js
var _ = require("lodash").runInContext();
```

**Comment by jlmorgan** [comment]
You sir, are aware of all things lodash it appears. = D

Thanks for the suggestion. I had considered making this a pull request into lodash proper but opted not to do so.

**Comment by jdalton** [comment]
Rock!

**Comment by jlmorgan** [comment]
If you see any other items of improvement, feel free to let me know. = D
